# Generated by Django 6.0.1 on 2026-02-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_team_description_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.CharField(choices=[('CHANCE', 'Chance Liga'), ('NHL', 'NHL')], default='CHANCE', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
