# Generated by Django 6.0.1 on 2026-02-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_team_league_alter_team_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.CharField(choices=[('CZE', 'Česko'), ('ATL', 'Atlantická divize'), ('MET', 'Metropolitní divize'), ('CEN', 'Centrální divize'), ('PAC', 'Pacifická divize')], default='CZE', max_length=5),
        ),
    ]
