# Generated by Django 6.0.2 on 2026-02-07 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_goal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['minute']},
        ),
        migrations.AddField(
            model_name='goal',
            name='is_penalty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='minute',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField(default=0)),
                ('card_type', models.CharField(choices=[('Y', 'Žlutá'), ('R', 'Červená')], max_length=1)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='main.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
            options={
                'ordering': ['minute'],
            },
        ),
    ]
