# Generated by Django 6.0.2 on 2026-02-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_goal_options_goal_is_penalty_goal_minute_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('Y', 'Žlutá'), ('R', 'Červená')], max_length=1, verbose_name='Typ karty'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='is_penalty',
            field=models.BooleanField(default=False, verbose_name='Penalta'),
        ),
    ]
