# Generated by Django 6.0.2 on 2026-02-08 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_card_card_type_alter_goal_is_penalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='is_penalty',
            field=models.BooleanField(default=False, verbose_name='Trestné střílení'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Brankář'), ('DF', 'Obránce'), ('FW', 'Útočník')], max_length=50),
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField(default=0)),
                ('duration', models.IntegerField(choices=[(2, '2 minuty'), (5, '5 minut'), (10, '10 minut'), (20, 'Do konce utkání')], default=2, verbose_name='Délka trestu')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='Důvod (faul)')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='main.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
            options={
                'verbose_name_plural': 'Tresty',
                'ordering': ['minute'],
            },
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
