# Generated by Django 6.0.2 on 2026-02-08 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_goal_is_penalty_alter_player_position_penalty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['minute'], 'verbose_name': 'Gól', 'verbose_name_plural': 'Góly'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Zápas', 'verbose_name_plural': 'Zápasy'},
        ),
        migrations.AlterModelOptions(
            name='penalty',
            options={'ordering': ['minute'], 'verbose_name': 'Trest / Karta', 'verbose_name_plural': 'Tresty a karty'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Hráč', 'verbose_name_plural': 'Hráči'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Tým', 'verbose_name_plural': 'Týmy'},
        ),
        migrations.AlterField(
            model_name='goal',
            name='is_penalty',
            field=models.BooleanField(default=False, verbose_name='Penalta / Trestné střílení'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='minute',
            field=models.PositiveIntegerField(default=0, verbose_name='Minuta'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player', verbose_name='Střelec'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_score',
            field=models.IntegerField(default=0, verbose_name='Skóre hosté'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='main.team', verbose_name='Hostující tým'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_score',
            field=models.IntegerField(default=0, verbose_name='Skóre domácí'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='main.team', verbose_name='Domácí tým'),
        ),
        migrations.AlterField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(verbose_name='Čas začátku'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('PRE', 'Neproběhlo'), ('LIVE', 'Živě'), ('FIN', 'Ukončeno')], default='PRE', max_length=4, verbose_name='Stav zápasu'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='duration',
            field=models.IntegerField(choices=[(2, '2 minuty / Žlutá karta'), (5, '5 minut / Červená karta'), (10, '10 minut'), (20, 'Do konce utkání / Červená karta')], default=2, verbose_name='Délka trestu / Typ karty'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='minute',
            field=models.PositiveIntegerField(default=0, verbose_name='Minuta'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player', verbose_name='Hráč'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Jméno hráče'),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(verbose_name='Číslo dresu'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Brankář'), ('DF', 'Obránce'), ('FW', 'Útočník')], max_length=50, verbose_name='Pozice'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='main.team', verbose_name='Tým'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(choices=[('CZE', 'Česko'), ('ATL', 'Atlantická divize'), ('MET', 'Metropolitní divize'), ('CEN', 'Centrální divize'), ('PAC', 'Pacifická divize')], default='CZE', max_length=5, verbose_name='Divize/Stát'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.CharField(choices=[('CHANCE', 'Chance Liga (Fotbal)'), ('NHL', 'NHL (Hokej)')], default='CHANCE', max_length=20, verbose_name='Soutěž'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL loga'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Název týmu'),
        ),
    ]
