# Generated by Django 6.0.2 on 2026-02-08 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_goal_options_alter_match_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['minute']},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
        migrations.AlterField(
            model_name='goal',
            name='is_penalty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goal',
            name='minute',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goal',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='main.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='main.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('PRE', 'Neproběhlo'), ('LIVE', 'Živě'), ('FIN', 'Ukončeno')], default='PRE', max_length=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Brankář'), ('DF', 'Obránce'), ('MD', 'Záložník'), ('FW', 'Útočník')], max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='main.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(choices=[('CZE', 'Česko'), ('ATL', 'Atlantická divize'), ('MET', 'Metropolitní divize'), ('CEN', 'Centrální divize'), ('PAC', 'Pacifická divize')], default='CZE', max_length=5),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.CharField(choices=[('CHANCE', 'Chance Liga'), ('NHL', 'NHL')], default='CHANCE', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField(default=0)),
                ('card_type', models.CharField(choices=[('Y', 'Žlutá'), ('R', 'Červená')], max_length=1)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='main.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
            options={
                'ordering': ['minute'],
            },
        ),
        migrations.DeleteModel(
            name='Penalty',
        ),
    ]
