# Generated by Django 6.0.2 on 2026-02-08 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_goal_options_alter_match_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField(default=0)),
                ('duration', models.IntegerField(default=2)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='main.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
            options={
                'ordering': ['minute'],
            },
        ),
    ]
