# Generated by Django 6.0.2 on 2026-02-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='current_elapsed_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='last_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
