# Generated by Django 6.0.2 on 2026-02-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_match_current_elapsed_seconds_match_is_running_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='last_start_time',
            new_name='current_period_start',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='current_elapsed_seconds',
            new_name='offset_minutes',
        ),
        migrations.RemoveField(
            model_name='match',
            name='is_running',
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('PRE', 'Neproběhlo'), ('LIVE', 'Probíhá'), ('PAU', 'Pauza'), ('FIN', 'Ukončeno')], default='PRE', max_length=4),
        ),
    ]
