# Generated by Django 6.0.2 on 2026-02-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_last_start_time_match_current_period_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='offset_minutes',
            new_name='current_elapsed_seconds',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='current_period_start',
            new_name='last_start_time',
        ),
        migrations.AddField(
            model_name='match',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('PRE', 'Neproběhlo'), ('LIVE', 'Živě'), ('FIN', 'Ukončeno')], default='PRE', max_length=4),
        ),
    ]
