# Generated by Django 6.0.2 on 2026-02-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_offset_minutes_match_current_elapsed_seconds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='current_elapsed_seconds',
        ),
        migrations.RemoveField(
            model_name='match',
            name='is_running',
        ),
        migrations.RemoveField(
            model_name='match',
            name='last_start_time',
        ),
    ]
